config/routes.rb
Rails.application.routes.draw do
  get 'game/play'
  match '/play', to: 'game#play', via: 'get'
  get 'home/setup'
  root 'home#setup'
  match '/questions/:id/grade', to: 'questions#grade', via: 'post'
  resources :questions
  match '/game/newteam', to: 'game#newteam', via: 'post'
  match '/game/continue', to: 'game#continue', via: 'post'
  match '/teams', to: 'teams#show', via: 'get'
  match '/admin/newgame', to: 'teams#newgame', via: 'delete'
  match '/admin/clearpoints', to: 'teams#clearpoints', via: 'delete'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	belongs_to :team
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers
	has_many :teams, through: :answers
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :answers
	has_many :questions, through: :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def play
    @team = Team.find(session[:team])
    @answered_questions = []
    @team.questions.each {|question| @answered_questions << question.number}
    @message = flash[:message]
    @points = flash[:points_lost]
    if @points != nil && @points != 0
      @team.points -= @points
      @team.save
      if @message == nil
        @message = "You broke the system."
      end
    end
    @status = flash[:status]
  end

  def newteam
    @team = Team.find_by(name: params[:teamname])
    if @team == nil
      @team = Team.create(name: params[:teamname], points: 0)
    end
    session[:team] = @team.id
  	redirect_to action: 'play'
  end

  def continue
    #grab info from params / session
    @team = Team.find(session[:team])
  	new_points = params[:points]
    question_id = params[:question_id]

    #create the appropriate answer link with the right number of points
    answer = Answer.find_by(team_id: @team.id, question_id: question_id)  #id with number??
    answer.update_attributes(points: new_points)
    
    if new_points.to_i < 0
      flash[:message] = new_points + " points lost."
      flash[:status] = "failure"
    else
      flash[:message] = new_points + " points earned."
      flash[:status] = "success"
    end

    #update the team's total points
    @team.points += new_points.to_i
    @team.save

  	redirect_to action: 'play'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def setup
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:update, :destroy]

  def grade
    @answer = params[:answer]
    num = params[:question]
    @question = Question.find_by(number: num)
    @team_id = session[:team]
   
    #let's make sure they're not cheating, by trying to resubmit their answer to the question
    @team_answer = Answer.find_by(team_id: @team_id, question_id: @question.id)
    @team_answer.update_attributes(text: @answer)
    if @team_answer == nil
      redirect_to "/game/play"
    elsif @team_answer.points < 0
      flash[:message] = "Sorry, you can only submit your answer once."
      redirect_to "/game/play"
    else
      @team_answer.points = - (@question.points / 2)
      @team_answer.save
    end
      flash[:points_lost] = @question.points / 2
  end


  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order(:number)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @team_id = session[:team]
    @question = Question.find_by(number: params[:id])

    #let's make sure they're not cheating, by trying to answer the question again
    if Answer.find_by(team_id: @team_id, question_id: @question.id) != nil
      flash[:message] = "Sorry, you can only view a question once."
      flash[:points_lost] = @question.points / 2
      redirect_to "/game/play"
    else
      Answer.create(team_id: @team_id, question_id: @question.id, points: 0)
    end

  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find_by(number: params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to '/questions', notice: 'Question was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to '/questions', notice: 'Question was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to '/questions', notice: 'Question was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:number, :points, :prompt, :tests, :input, :solution)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	def show
		@teams = Team.all
		@questions = Question.all
	end
	def newgame
		Team.destroy_all
		Answer.destroy_all
		redirect_to '/questions'
	end
	def clearpoints
		Answer.destroy_all
		Team.all.each do |team|
			team.points = 0
			team.save			
		end
		redirect_to '/questions'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/game/play.html.erb
<style>
	#message {
		display: inline-block;
		padding: 10px;
		border-style: solid; 
		border-radius: 10px; 
		border-width:3px;
		font-size: 24px;
		font-weight: bolder;
		line-height: 30px;
	}
	.failure {
		background-color: pink;
		color: red;
		border-color: red;
	}
	.success {
		background-color: lightgreen;
		color: green;
		border-color: green;
	}
</style>
<% if @status != nil %>
	<div align="center" id="message" class="<%= @status %>"><%= @message %></div>
<% elsif @message != nil %>
	<div align="center" id="message" class="failure"><%= @message %><br> You lose <%= @points %> points.</div>
<% end %>

<h1>Jeopardy</h1>
<style>
	td,th {
		font-size: 30px;
		font-weight: bolder;
		padding: 30px;
	}
	body {
		text-align: center;
	}
	h1 {
		font-size: 100px;
	}
</style>
<h2>Team <%= @team.name %> has <%= @team.points %> points.</h2>
<table align="center">
<% (1..5).each do |i| %>
<tr>
<% (0..2).each do |j| %>
<% question_number = (j*5+i) %>
<% points = i*100 %>
<% if @answered_questions.include?(question_number) %>
<td>
<span style="color:grey"><b><%= points %></b></span>
</td>
<% else %>
<td>
<a href="/questions/<%= question_number %>"><%= points %></a>
</td>
<%end%>
<%end%>
</tr>
<% end %>
</table>
<div style="height:50px"></div>
<%= link_to "Click Here for the Full Standings", "/teams", style: "font-size: 18px; font-weight: bolder" %>

app/views/home/setup.html.erb
<div style="height:100px"></div>
<div align="center">
<h1 style="font-size: 50px;">Jeopardy</h1>
<h3>Enter your team name</h3>

<%= form_tag("/game/newteam", method: "post") do%>
	Team Name:
	<%= text_field_tag :teamname %>
	<%= submit_tag "Continue" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jeopardy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="/ace-builds/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :prompt %><br>
    <%= f.text_area :prompt %>
  </div>
  <div class="field">
    <%= f.label :inputs %><br>
    <%= f.text_area :input %>
  </div>
  <div class="field">
    <%= f.label :tests %><br>
    <%= f.text_area :tests %>
  </div>
  <div class="field">
    <%= f.label :solution %><br>
    <%= f.text_area :solution %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', '/questions/' + @question.number.to_s %> |
<%= link_to 'Back', questions_path %>

app/views/questions/grade.html.erb
<script src="http://code.jquery.com/qunit/qunit-1.14.0.js"></script>
  <link rel="stylesheet" href="http://code.jquery.com/qunit/qunit-1.14.0.css">

  <style>
  pre {
  	text-align:left;
  	width:500px; 
  	position:relative; 
  	left:10%;
	white-space: pre-wrap;       /* css-3 */
	white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
	white-space: -pre-wrap;      /* Opera 4-6 */
	white-space: -o-pre-wrap;    /* Opera 7 */
	word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
#your-result {
	font-size:30px; 
	font-weight:bold; 
	padding-top:100px; 
	padding-bottom:50px; 
	float:right;
	position: relative;
	right: 20%;
}
#warning {
	align:center; 
	position: fixed; 
	bottom: 0px; 
	width: 100%; 
	left: 0px;
	color: black;
	background-color: lightblue; 
	border-radius: 5px;
	border-style: solid;
	border-color: black;
	border-width: 3px;
	line-height:20px; 
	font-size: 16px;
}
body {
	margin-bottom: 350px;
}
  </style>

  <div id="qunit"></div>
  <div id="qunit-fixture"></div>
  <div align="center" style="text-align:center;">
  <div id="your-result"></div>
  <div style="float:left">
  <h2>Your Solution:</h2>
<pre id="their-solution" style="font-size:18px"><%= raw(@answer) %></pre>
  <h2>Our Solution:</h2>
<pre id="our-solution" style="font-size:18px"><%= raw(@question.solution) %></pre>
  </div>
 </div>
 <div id="warning"><b>Do not go back or attempt to reload this page. You will not be able to view this page again and you will lose any points you might have earned. If no button appears after a few seconds, your answer is incorrect. <a href="/game/play">Navigate back to the game page.</a></b></div>
<script type="text/javascript">
	var answer = <%= raw(@answer) %>
	var oursolution = <%= raw(@question.solution) %>
	<% input_arr = @question.input.split("\r\n") %>
<% input_arr.each do | inp | %>

QUnit.test( "testing on `<%= inp %>` => ", function( assert ) {
  assert.deepEqual( answer.apply(this,[<%= inp %>]), oursolution.apply(this,[<%= inp %>])), "what's up";
});

<% end %>

function formHTML(result){ 
	var points = 0;
	if(result == "Success"){
		points = <%= @question.points %>;
	} else{
		points = <%= @team_answer.points %>
	}
	var str = '<%= form_tag "/game/continue" do %><input type="hidden" name="points" value="' + points + '" /><input type="hidden" name="question_id" value="<%= @question.id %>" /><%= submit_tag "result", class: "button", style: "font-size: 40px" %><% end %>';
	return str.replace("result", result);
}

QUnit.done(function( details ) {
	  console.log( "Total: ", details.total, " Failed: ", details.failed, " Passed: ", details.passed, " Runtime: ", details.runtime );

	if(details.failed === 0){
		document.getElementById('your-result').innerHTML = formHTML("Success")
	} else{
		document.getElementById('your-result').innerHTML = formHTML("Failure")
	}
	
	// document.getElementById('our-solution').innerHTML = oursolution
	// document.getElementById('their-solution').innerHTML = answer

});
</script>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Points</th>
      <th>Prompt</th>
      <th>Tests</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.number %></td>
        <td><%= question.points %></td>
        <td><%= question.prompt %></td>
        <td><%= question.tests %></td>
        <td><%= link_to 'Show', '/questions/' + question.number.to_s %></td>
        <td><%= link_to 'Edit', '/questions/' + question.number.to_s + '/edit' %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Question', new_question_path %></p>
<div style="float:right">
<p><%= link_to 'Reset Game', "/admin/clearpoints", method: :delete, data: { confirm: 'This will clear all current points. Are you sure you want to continue?'} %></p>
<p><%= link_to 'New Game', "/admin/newgame", method: :delete, data: { confirm: 'This will delete all teams, clear all scores, and reset the game. Are you sure you want to continue?'} %></p>
</div>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div style = "height: 20px"></div>
<style type="text/css">
	textarea {
	border: 5px solid black;
	border-radius: 10px;
	font-size: 20px;
}
#prompt{
	font-size: 30px;
	line-height: 40px;
}
h3{
	font-size: 40px;
}
h1 {
	font-size: 60px;
}
pre {
  	width:500px; 
  	border-radius: 10px;
  	border: 3px solid black;
  	font-size: 18px;
	white-space: pre-wrap;       /* css-3 */
	white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
	white-space: -pre-wrap;      /* Opera 4-6 */
	white-space: -o-pre-wrap;    /* Opera 7 */
	word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
#editor { 
	width: 80%;
    height: 300px;
    margin-left: 10%;
    margin-right: 10%;
    border: 3px solid black;
    border-radius: 5px;
    font-size: 1.3em;
}
</style>
<div align="center">
<p id="notice"><%= notice %></p>

  <h1>Question:</h1>
  <div style="height: 10px"></div>
  <div id="prompt"><%= @question.prompt %></div>
  <div style="height: 20px"></div>

  <h3>Examples:</strong></h3>
 <pre> <%= @question.tests %></pre>
	<h3>Your Answer:</h3>
	<div style="height:20px"></div>
</div>
<div id="editor">
</div>
<!-- a hidden form to help submitting data. -->
	<%= form_tag("/questions/" + params[:id] + "/grade", method: 'post') do %>
		<%= hidden_field_tag :answer %>
		<%= hidden_field_tag :question %>
	<% end %>
	<div style="text-align:center;">
	<button class="button" style="margin-top:20px;font-size: 40px" onclick="submit()">Submit</button>
</div>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/xcode");
    editor.getSession().setMode("ace/mode/javascript");

function submit() {
	var answer = editor.getValue();
	var url = "/questions/" + <%= params[:id] %> + "/grade";
	var question = <%= params[:id] %>;

	$('#question')[0].value = question;
	$('#answer')[0].value = answer;

	document.getElementsByTagName('form')[0].submit();
}
</script>